modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
displayTest="MATCH_VERSION"
logoFile="logo.png"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.irons_spells_more_interaction]]
modId="curios"
mandatory=false
versionRange="[5.7.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.irons_spells_more_interaction]]
modId="irons_spellbooks"
mandatory=false
ordering="AFTER"
side="BOTH"

[[dependencies.irons_spells_more_interaction]]
modId="traveloptics"
mandatory=false
ordering="AFTER"
side="BOTH"

[[dependencies.irons_spells_more_interaction]]
modId="cataclysm_spellbooks"
mandatory=false
ordering="AFTER"
side="BOTH"

[[dependencies.irons_spells_more_interaction]]
modId="alshanex_familiars"
mandatory=false
ordering="AFTER"
side="BOTH"

[[dependencies.irons_spells_more_interaction]]
modId="legendary_spellbooks"
mandatory=false
ordering="AFTER"
side="BOTH"

[[dependencies.irons_spells_more_interaction]]
modId="wind_spellbooks"
mandatory=false
ordering="AFTER"
side="BOTH"


# 以下、traveloptics / cataclysm_spellbooks / alshanex_familiars /
# legendary_spellbooks / wind_spellbooks を同じ書式で並べる

